### ISSUE TITLE
feature request: list chests

### ISSUE THREAD

**Issue by meoso** [tim-savage/SavageDeathChest#11]
On rare occasion, the chest is placed a bit far from the death location.  Mostly it is easily visible, but on occasion it can not be found.  I was forced to look into the sqllite db to find it.

Feature Request: `/deathchest list` which will list the player's chest locations and permission `deathchest.player.list` to enable.

**Comment by tim-savage** [comment]
structural changes have been made to the plugin to allow features like this to be added in the future. this will likely be added in a future version after a stable 1.13.x version is released.
