### ISSUE TITLE
feature request: dynmap itegration

### ISSUE THREAD

**Issue by meoso** [tim-savage/SavageDeathChest#12]
feature request: display death chests on [DynMap](https://www.spigotmc.org/resources/dynmap.274/) like [CenoTaph](https://www.spigotmc.org/resources/cenotaph.2180/) does.

**Comment by tim-savage** [comment]
structural changes to the plugin have been made in the upcoming 1.13.x version. This feature will likely be added to a future version after the 1.13.x version is deemed stable.
