### ISSUE TITLE
Not working on 1.13

### ISSUE THREAD

**Issue by Castiella** [tim-savage/SavageDeathChest#16]
Plugin is green in /pl however it doesnt spawn chests for anyone, in any worlds. (it did on 1.12 and the config is set up correctly)

No weird output in console, but heres the latest log anyway just in case you want it 
[latest.log](https://github.com/tim-savage/SavageDeathChest/files/2349196/latest.log)

**Comment by k9lego** [comment]
@Castiella I've found it works for 1.13.1 PaperMC.

**Comment by tim-savage** [comment]
I've started work on an updated version for 1.13.x. I just need to update the API calls to other protection plugins before I can push out a release.
