### ISSUE TITLE
replaceable-blocks in default config and above build height

### ISSUE THREAD

**Issue by mart-r** [tim-savage/SavageDeathChest#18]
Hi!

Would just like to point out that the default config `replaceable-blocks` section should include
`- CAVE_AIR` 
As otherwise, the plugin fails in caves (which is not what people expect, I'm guessing).

And if you die far enough above build height, the plugin will fail to find a place for the chest. I recommend a similar workaround as you do for players below 1 in `LocationUtilities.java` (plus a config entry).

All the best.

**Comment by tim-savage** [comment]
Thanks for pointing these issues out, I was unaware of both conditions. I've added your suggestions to the latest development version.
