### ISSUE TITLE
DeathBukkit-like features

### ISSUE THREAD

**Issue by minetonight** [tim-savage/SavageDeathChest#2]
Hi,

Compliments for your plugin. So far it looks great and better than DeathBukkit in many ways. 
But could you add two features to make that the best deathChest plugin out there?
1.  command "/deathchest location" - tells the location of the death chests. I know of your "Compass" plugin, but it does not work with GriefPreventionWell. And you have all the locations in the dc-storage.
2. Right click on sign for quick-loot - that is a habit feature, as we used to restore our inventory with right click.
3. Timed protection - fresh DC's are protected, but abandoned ones are unlocked. That allows not to lose items in the server.

Cheers

**Comment by tim-savage** [comment]
these features will be considered for a future version.
