### ISSUE TITLE
Missing maven repos for some dependencies

### ISSUE THREAD

**Issue by RoboMWM** [tim-savage/SavageDeathChest#33]
Failed to execute goal on project SavageDeathChest: Could not resolve dependencies for project com.winterhaven-mc:SavageDeathChest:jar:1.13.0: The following artifacts could not be resolved: com.winterhaven-mc:world-manager-lib:jar:1.0.6, 
com.winterhaven-mc:message-manager-lib:jar:1.0.1, 
com.winterhaven-mc:sound-config-lib:jar:1.0.1, 
com.palmergames:Towny:jar:0.93.0.0, 
com.massivecraft:factions:jar:2.14.0, 
com.winterhaven-mc:RoadBlock:jar:1.13.1: Could not find artifact com.winterhaven-mc:world-manager-lib:jar:1.0.6

**Comment by tim-savage** [comment]
I do not currently have a public maven repo. These libraries are available[ here](https://github.com/tim-savage/PluginUtilities). They can be compiled and installed in your local maven repository, and then will be available when building this plugin. Sorry for the inconvenience, I intend to re-establish a public maven repo at some time in the future.

**Comment by RoboMWM** [comment]
Ok thanks. FYI, bintray provides free maven repo hosting for open source projects. Jitpack is another alternative that can compile and add your artifacts to its maven repo automatically. (I use the latter for GP.)

**Comment by RoboMWM** [comment]
Still missing things like towny and roadblock. And one of those libs (the teleport lib) doesn't compile due to lacking repo. :c

**Comment by tim-savage** [comment]
Roadblock is available in its own repository, [here](https://github.com/tim-savage/RoadBlock). The teleport lib is a work in progress, and is not currently used by any of my plugins. Towny is available on the palmer games website. http://towny.palmergames.com
