### ISSUE TITLE
Chest sneak-punch causes some of the items to disappeared and i can not disable sneak-punch; and protection area after setblock

### ISSUE THREAD

**Issue by MaoDoBan** [tim-savage/SavageDeathChest#37]
I am using SavageDeathChest v1.13.0 beta 1. My server is running git-Paper-469 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT). I use LuckPerms 4.3.11 for permissions.

1. When i do the sneak-punch in a chest without inventory for all the items, it makes the exceding ones disappear instead  of dropping to the ground or staying on the the chest (i prefer the later one).

2. I can not disable sneak-punch on the configuration file neither configure the permission node deathchest.loot to false.

3. If i use setblock (stone for example) in the chest, the place where it was gets protected and i can not put any block there. Detail: chest-protection: true.

**Comment by tim-savage** [comment]
1. This was an oversight on my part. I have changed the behavior of the plugin to keep items in a chest when a player does not have room in their inventory for all chest items when a sneak-punch is performed.

2. Config setting and permission node for death chest looting have been restored.

3. I'm not exactly sure what you mean. If this behavior still happens with the recently release 1.13.1-beta1 version, please open another issue with more details.
