### ISSUE TITLE
[Suggestion] Send death chest coordinates and keep them in a deathcheats.log

### ISSUE THREAD

**Issue by MaoDoBan** [tim-savage/SavageDeathChest#38]
Send to the player chat (and console) the death chest coordinates after the player died, and keep a deathcheats.log with all the coordinates of those chests. It would make it easier to track them.

**Comment by tim-savage** [comment]
Players can now list their chest locations by command if the requisite permission is granted. (It defaults to false, so players need to have the _deathchest.list_ permission explicitly set.)

There is a custom message that is disabled by default on chest deployment, and there are now placeholders for chest location coordinates. It should be possible to change the message to include the chest coordinates and then enable the message in the language yaml file.

Chest deployments are currently logged in the server log file. I will consider creating a separate log file in a future version.
