### ISSUE TITLE
no one can access the chest

### ISSUE THREAD

**Issue by comonier** [tim-savage/SavageDeathChest#43]
I have a problem I am owner [operator] of 1 server 1 players fell into void and the chest was generated in block 1 - I was trying to create 1 elevator for him to pick up the items and accidentally opened and closed the chest, the cover was left open, when he tried to receive received a message saying that there is already another player accessing the chest. I as an operator also get the same message, and I can not even break the chest nor open to pick up the items, nor he as owner

**Comment by comonier** [comment]
after some time - player back and open with no problema =/

solved

**Comment by tim-savage** [comment]
That's an interesting situation. I think it may be a bug that needs to be addressed in the server. A player who dies should be removed from the list of viewers for any inventories they were viewing at the time of death. I'm not sure that can even be done by a plugin. Using the quick-loot feature (sneak-punch chest) would also prevent that from happening.
