### ISSUE TITLE
If the player has no chest, no loots on the floor

### ISSUE THREAD

**Issue by Endothelium** [tim-savage/SavageDeathChest#45]
Hello,

If the player has no chest equiped, there are no loots on the floor.

I could use the option `require-chest: false`, but it can be problematic if the plugin bug and the user loose his stuff.

Is there a way to let the stuff drop on the floor if there is no possibility to store it in a chest? Thanks

I am using Spigot 1.13.2

**Comment by tim-savage** [comment]
There is a bug in the require-chest code. A fixed version will be available soon.
