### ISSUE TITLE
Feature Request: Access chests in protected regions

### ISSUE THREAD

**Issue by OpalMoonstride** [tim-savage/SavageDeathChest#47]
Could you possibly add an option to allow chests to spawn, and be accessed by the player which died, even if the player dies in a protected region, such as worldguard, or towny?

For clarification: If a player dies at spawn, which is protected by towny, and a deathchest is placed, the player which died cannot access his/her chest. So far, the only way around this is to not spawn chests in protected regions. 

Thanks, so much!

**Comment by tim-savage** [comment]
There appears to be a bug in the check-on-access feature. I've only tested with worldguard, but it appears that *only* opening a chest by clicking the chest itself is being blocked when check-on-access is set to false in config.yml.

My brief testing indicates that a chest can still be opened by clicking the attached sign, and that a chest can be broken, or auto-looted by sneak-punching, when check-on-access is configured false. You may wish to inform your users of these workarounds until a fixed version is released.

If you experience different results from what I've described above, please follow up with information on the specific plugin and the method of access being denied, so I can take that into account when fixing this issue. Thanks for the report!

**Comment by OpalMoonstride** [comment]
Ah! Well that's just fine, then. I can deal with the work-around. 

Thanks, so much!
