### ISSUE TITLE
[Feature request] Logging of chest place failure + items dropped

### ISSUE THREAD

**Issue by mart-r** [tim-savage/SavageDeathChest#51]
Sometimes the death chest doesn't deploy and the people complain.
It would be lovely if we there was a log kept of who died, when and where and why the death chest was not deployed. Furthermore, the items dropped could be logged.

This, of course, could be turned off (even by default) in the config.

**Comment by Gnoarn** [comment]
Having the same issue. Most commonly in the end. and yes it would be great to have a log when and where.

**Comment by mart-r** [comment]
I'm fairly certain the issue is the fact that the config got changed.
Previously there were entries like `check-on-place`, now the entries go `ignore-on-place` (and obviously you'll have to reverse the boolean).

Given the above, you've most likely set it to NOT check on placement for WorldGuard and because of the update, the setting is in its default (`ignore-on-place: false`) meaning it'll NOT ignore (thus checking) the region and won't place the chest.

**Comment by tim-savage** [comment]
Will add logging in a later version.
