### ISSUE TITLE
Doubles items in 1.14.2

### ISSUE THREAD

**Issue by OverDhill** [tim-savage/SavageDeathChest#59]
When used in 1.14.2 the chest has your items as well as a duplicate set laying around the outside of the chest when you die.

Needs updating for 1.14.2

**Comment by AryToNeX** [comment]
I can confirm this issue; @tim-savage is this plugin still maintained?

**Comment by LickTheCheese** [comment]
i also have this issue

**Comment by LickTheCheese** [comment]
However, it appears that if you disable signs, it will no longer dupe the items.

Possibly the plugin crashing when it tries to place a sign and then not deleting the items?

[here are some relevant logs](https://paste.tildeverse.org/?bce31f2b4f710398#2qFm5G6c4QuUUTP7UqPPEEiYFvcQboSQK8yiHCbyZvpV)

**Comment by tim-savage** [comment]
This issue was caused by material names for signs being changed in the bukkit api. Fixed in latest version.
