### ISSUE TITLE
version 1.16.0 does't work properly on PaperSpigot

### ISSUE THREAD

**Issue by imfrea** [tim-savage/SavageDeathChest#61]
Even players have items in their inventory, but when they dead SavageDeathChest still notice "You had no inventory to place in a death chest"
I tried on Spigot 1.16 it works but Paper not（I'm using Paper 1.16 #100 Build）
this problem same are existed on older version of SavageDeathChest

**Comment by tim-savage** [comment]
Is it possible that another plugin is manipulating the player inventory on a death event? All of the testing I've done has been on recent versions of Paper, and I've not encountered this behavior.

Also check that your config.yml file is up to date, perhaps make a backup and allow the plugin to install a new version on server restart or plugin reload.

**Comment by imfrea** [comment]
Thank , I finally found that it is [an inventory snapshot plugin](https://www.spigotmc.org/resources/22027/) coursed this problem . It's not a Paper's issue, sorry.
