### ISSUE TITLE
[SUGGESTION] Lands compatibility

### ISSUE THREAD

**Issue by srnyx** [tim-savage/SavageDeathChest#64]
Would be nice if players could open the person-they-killed's death chest even if they are in a land where they can't open containers.
**Plugin:** https://www.spigotmc.org/resources/53313

**Comment by srnyx** [comment]
@tim-savage

**Comment by tim-savage** [comment]
I've uploaded another prerelease version that attempts to integrate with the Lands plugin. As it is a for-pay plugin, I have no way to test it without purchasing the plugin. I've made my best attempt, but can make no promises. Give it a try and let me know if it works.

**Comment by srnyx** [comment]
> Give it a try and let me know if it works.

```
[17:53:58 WARN]: [SavageDeathChest] An error occurred checking for block place permission with Lands v5.24.10
[17:53:58 WARN]: [SavageDeathChest] An error occurred checking for block place permission with Lands v5.24.10
```

**Comment by tim-savage** [comment]
I've just published another prerelease version, that hopefully fixes the issue with Lands integration. If you could test it for me and acknowlege whether it is working or not, I'd be grateful.

https://github.com/tim-savage/SavageDeathChest/releases/tag/v1.18.6-SNAPSHOT
