### ISSUE TITLE
Vehicles are used as death chest

### ISSUE THREAD

**Issue by srnyx** [tim-savage/SavageDeathChest#67]
If `require-chest` is `true`, the plugin will use vehicles from [Vehicles](https://www.spigotmc.org/resources/12446) because they are chests (when not placed and sitting in the inventory)

**Comment by tim-savage** [comment]
I'm not able to reproduce this behavior. The code that checks for a chest in a player's inventory is looking specifically for an ItemStack of Material.CHEST. In my testing, other containers such as minecarts, barrels etc. did not match, and caused the inventory items to drop when the require-chest feature is enabled.

My tests were performed with the latest version of Paper 1.18 (build 124).

**Comment by srnyx** [comment]
> I'm not able to reproduce this behavior. The code that checks for a chest in a player's inventory is looking specifically for an ItemStack of Material.CHEST. In my testing, other containers such as minecarts, barrels etc. did not match, and caused the inventory items to drop when the require-chest feature is enabled.
> 
> My tests were performed with the latest version of Paper 1.18 (build 124).

[Vehicles](https://www.spigotmc.org/resources/12446) uses chests as vehicles
![image](https://user-images.githubusercontent.com/25808801/147864493-f134da7f-800e-426b-8359-edc44924a272.png)

**Comment by tim-savage** [comment]
Ah, I didn't realize Vehicles was another plugin, I thought it was a reference to the bukkit api interface of the same name.

As there is no publicly available api for the Vehicles plugin, I'm afraid there's nothing I can do on my end. Perhaps the Vehicles author could use a different block type for their vehicles? Seems to me a minecart might be more appropriate, if a completely custom block type is not possible.

**Comment by srnyx** [comment]
> Ah, I didn't realize Vehicles was another plugin, I thought it was a reference to the bukkit api interface of the same name.
> 
> As there is no publicly available api for the Vehicles plugin, I'm afraid there's nothing I can do on my end. Perhaps the Vehicles author could use a different block type for their vehicles? Seems to me a minecart might be more appropriate, if a completely custom block type is not possible.

What if you made SavageDeathChest only use chests that are nameless?
