### ISSUE TITLE
Free chest permission not working

### ISSUE THREAD

**Issue by srnyx** [tim-savage/SavageDeathChest#69]
I gave the VIP group the `deathchest.freechest` permission, but it still uses chests from player's inventory when they die.
And when they don't have a chest it just drops it on the ground.

**Comment by tim-savage** [comment]
deathchest.freechest permission is working as intended.
Tested with Paper 1.18.1-144 and LuckPerms 5.3.79 and 5.3.98.

**Comment by srnyx** [comment]
> deathchest.freechest permission is working as intended. Tested with Paper 1.18.1-144 and LuckPerms 5.3.79 and 5.3.98.

Sorry, had it denied on a higher-up group that I inherited.
