### ISSUE TITLE
Players can access Death Chest even if Protected.

### ISSUE THREAD

**Issue by D1p4k** [tim-savage/SavageDeathChest#71]
Hello,
The Plugin does not seem to cancel the Event of opening the Chest
If you open it it will just say "Death chest belonging to OGzoro is protected from looting for 59 minutes."
Could not find something in the Config to manage this.

I am using the Newest Version of the Plugin.
And Paper 1.18.1
![2022-01-30_13 40 20](https://user-images.githubusercontent.com/82884007/151700296-4233053f-5d71-46df-9728-5801c7210d2d.png)
![2022-01-30_13 40 22](https://user-images.githubusercontent.com/82884007/151700299-3fdf3f57-0ba9-477b-920b-ac0d7424684c.png)

**Comment by tim-savage** [comment]
You are correct, I missed a cancel event statement. A new version has been posted here and on spigotmc.org.

Thanks for the report, nice catch!
