### ISSUE TITLE
Double Chest are NOT Protected

### ISSUE THREAD

**Issue by D1p4k** [tim-savage/SavageDeathChest#72]
If someone generates a double chest it will be not be Protected from opening.

Tried reinstalling, Restarting.

**Comment by D1p4k** [comment]
The Issue is just gone.
idk

**Comment by tim-savage** [comment]
Ok, that's good, I guess. Maybe it was a bug in a particular server build. If it comes back, you can open a new issue, or post in this thread and we'll get it sorted.
